### ISSUE TITLE
bbox_point_tracking_sequence

### ISSUE THREAD

**Issue by jmwang0117** [real-stanford/im2Flow2Act#5]
Hi,

Thanks for your excellent work!

How did you generate the **"bbox_point_tracking_sequence"**? Did you track the whole image first and then filter it with the box?

Also, does the 32 x 32 here mean that each box has 1024 points, or does the whole image have 1024 points?

Looking forward to your reply, thank you!

**Comment by mengdaxu** [comment]
Hi, 

Thanks for your kind words. 

For real-world dataset, we first use grounding DINO to extract the object bbox and then sample points inside of it. 
For simulation dataset, we first track whole image to get the moving object rough location and sample densely around it. We didn't use the grounding DINO at the beginning as we worried whether it can work on simulation. However, it turns out it is quite robust across sim and real. So you can also use the same way to process simulation dataset as the real-world one.
