### ISSUE TITLE
Is the checkpoint overfitted?

### ISSUE THREAD

**Issue by TaoshuaiZ** [real-stanford/im2Flow2Act#8]
Hello,

I am very interested in your work.

I am running the flow generation `inference.py` and I use the realworld_human_demonstration pickNplace dataset. The text is "move the green cup onto the red plate.", however, the generated flow is like a pouring flow. I am confused about this result. Is the checkpoint overfited to the pouring task?

![pickNplace](https://github.com/user-attachments/assets/5aea152a-1f12-4190-bdb7-acd233e7b1e3)

**Comment by mengdaxu** [comment]
Thank you for sharing your findings! The checkpoint we released was only trained on simulated data, not on real-world data. To get it to perform well in real-world situations, you’ll need to train it with actual data from real environments.

Your observation is interesting—it shows that the model, even when trained only in simulation, can somewhat adapt to real-world tasks. The reason you observe pouring flow might be because, in the simulation, the pouring task uses a "red bowl" as the target, while the pick-and-place task uses a green plate. The learned model is more sensitive to the color in this case, instead of actual object.

**Comment by TaoshuaiZ** [comment]
Thanks sincerely for your reply. Then I understand why this result happens. 

I have a question about the generalizability of the flow generation model. If I want to complete the pickNplace task with an object unseen in the training set. Will this succeed? Do you have some findings in your research?

**Comment by henry0922** [comment]
I think it is indeed overfitting. For the same image, no matter how the text is modified, the generated flow is always similar.

**Comment by mengdaxu** [comment]
> I think it is indeed overfitting. For the same image, no matter how the text is modified, the generated flow is always similar.

Overfitting and the inability to generalize are quite different. Given the relatively small training dataset collected for both simulated and real-world tasks, the model may struggle to adapt to different types of text. For our learned model, it can still generate different types of flow based on the specific tasks.

**Comment by mengdaxu** [comment]
> Thanks sincerely for your reply. Then I understand why this result happens.
> 
> I have a question about the generalizability of the flow generation model. If I want to complete the pickNplace task with an object unseen in the training set. Will this succeed? Do you have some findings in your research?

We did not evaluate the generalization capability of our flow generation model. If the current model struggles to generalize, my hypothesis is that additional objects may need to be collected to achieve a certain level of generalization.
